### ISSUE TITLE
Cleanup Code Validation and Reporting

### ISSUE THREAD

**Issue by d3viant0ne** [babel/babel-loader#275]
- [x] More robust travis build ( should validate against what Webpack supports ) #278
- [x] Discuss moving to eslint with @danez 
- [x] Execute conversion to eslint using `eslint-config-babel` as a base #281
- [x] Branch protection on `master`.
- [x] Coverage generation & PR reporting via codecov.io #278
- [x] Changelog generation, commit format enforcement #279
- [x] Issue & PR Github Templates - `Webpack standard`
- [x] Contributor Guide - `Webpack standard`

> More to follow as I find it ...

**Comment by danez** [comment]
Oh i never noticed it is using jshint. 👍  for the move to eslint, not sure which config tho, `eslint-config-babel` might be a good start.

**Comment by d3viant0ne** [comment]
I usually try to keep code styles inline with parent repos, so in this case `eslint-config-babel` is a perfect place to start  :)
